version: "2.27.0"
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "5000:5000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
