version: "2.27.0"
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      # node-app-container doesn't running until mongo, and redis containers is running
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
