version: "2.27.0"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
